const fs = require('fs');
const path = require('path');

const iconDir = path.join(__dirname, 'icon');
const targetFile = path.join(__dirname, 'mobile', 'src', 'components', 'SvgIcons.ts');

const files = fs.readdirSync(iconDir);
const svgs = {};

files.forEach(file => {
    if (file.endsWith('.svg')) {
        const key = file.replace('--big.svg', '').replace('.svg', '');
        const content = fs.readFileSync(path.join(iconDir, file), 'utf8');
        // Remove comments
        const cleanContent = content.replace(/<!--[\s\S]*?-->/g, '').trim();
        svgs[key] = cleanContent;
    }
});

const fileContent = `// Automatically generated by dump_svgs.js
export const SVG_ICONS: Record<string, string> = ${JSON.stringify(svgs, null, 2)};
`;

fs.mkdirSync(path.dirname(targetFile), { recursive: true });
fs.writeFileSync(targetFile, fileContent, 'utf8');
console.log('✅ Generated SvgIcons.ts with', Object.keys(svgs).length, 'icons.');
