#!/usr/bin/env bash
#
# Print every Supabase migration, in order, as one script.
#
# The Supabase SQL editor takes one paste at a time, and running thirteen
# files by hand invites running them out of order or missing one. Every
# migration is guarded (IF NOT EXISTS / IF EXISTS), so the bundle is safe to
# run on a fresh database and safe to run again on one that is up to date.
#
#   ./scripts/bundle-migrations.sh > /tmp/termax-migrations.sql
#
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/backend/src/scripts/migrations"

cat <<'HEADER'
-- ─────────────────────────────────────────────────────────────────────
--  Termax — all migrations, in order.
--
--  Generated by scripts/bundle-migrations.sh; edit the individual files
--  under backend/src/scripts/migrations/, never this output.
--
--  Safe to run more than once.
--
--  This assumes the base schema (backend/src/scripts/supabase_schema.sql)
--  already exists — every migration here alters or references those tables.
--  On a brand-new project run that file first.
-- ─────────────────────────────────────────────────────────────────────

BEGIN;

-- Seven of these default an id to uuid_generate_v4(). The base schema
-- creates the extension, but a bundle that assumes someone ran that first
-- fails halfway through on a database where it is missing, leaving the run
-- rolled back with no obvious reason. Cheap to be self-sufficient.
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
HEADER

for f in "$DIR"/*.sql; do
    printf '\n\n-- ═══════════════════════════════════════════════════════════════\n'
    printf -- '-- %s\n' "$(basename "$f")"
    printf -- '-- ═══════════════════════════════════════════════════════════════\n\n'
    cat "$f"
done

printf '\n\nCOMMIT;\n'
